### ISSUE TITLE
(helm) ingress path (help wanted)

### ISSUE THREAD

**Issue by Hokwang** [opendistro-for-elasticsearch/opendistro-build#299]
Hi,

I am behind the corporate proxy and install odfe using helm. 
And I use ingress-nginx, local kubernetes cluster (not public cloud).
also use tls I created.

I want to use company.com/odfe-stage for es, for example.

In this case, how can I do?

1. kibana ingress path setting : is this right?
```
kibana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    path: /kibana
  config:
    server.basePath: /kibana
    server.rewriteBasePath: true
```

2. es ingress path setting : is this right?
```
elasticsearch:
  client:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
      path: /es
```

I am trying rewrite-target: / and /$1 and $2 ...
and force-ssl-redirect : "true" or "false" ...
but still don't know
```
$ curl -XGET "https://company.net/es" -u admin:admin -k
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>
```

**Comment by gsmith-sas** [comment]
@Hokwang Here is a sample someone else on my team put together for handling Kibana ingress (but with no TLS).  Since I didn't write it, I can't explain it; but I've been told it works.

```
# Kibana helm chart overrides

kibana:
  extraEnvs:
  - name: SERVER_BASEPATH
    value: /kibana

  service:
    type: ClusterIP
    nodePort: null

  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite (?i)/kibana/(.*) /$1 break;
        rewrite (?i)/kibana$ / break;
      nginx.ingress.kubernetes.io/rewrite-target: /
    enabled: true
    hosts:
    - host.mycluster.example.com
    path: /kibana

```

**Comment by Hokwang** [comment]
@gsmith-sas thanks for your comment, I will try that, but first problem is elasticsearch. don't know why I can't access. I will raise another issue.

**Comment by Hokwang** [comment]
In my case, basic solution is below.
```
kibana:
  extraEnvs:
    - name: SERVER_BASEPATH
      value: /kibana

  ssl:
    kibana:
      enabled: true
      existingCertSecret:
      existingCertSecretCertSubPath: kibana-crt.pem
      existingCertSecretKeySubPath: kibana-key.pem
      existingCertSecretRootCASubPath: kibana-root-ca.pem

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    path: /kibana(/|$)(.*)
    hosts: company.net
    tls:
      - secretName: ingress-tls
        hosts:
          - company.net
```
