### ISSUE TITLE
Hook up AD integration test with distribution

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opendistro-for-elasticsearch/opendistro-build#312]
Please include both AD and AD kibana, both should already have CI/CD set up.

https://github.com/opendistro-for-elasticsearch/anomaly-detection/blob/master/.github/workflows/CD.yml
https://github.com/opendistro-for-elasticsearch/anomaly-detection-kibana-plugin/blob/master/.github/workflows/CD.yml

**Comment by weicongs-amazon** [comment]
We will start working on the AD plugin next week. 
And talked to @ohltyler, he will help to share the instructions about how to run the kibana integration tests against remote kibana server

**Comment by weicongs-amazon** [comment]
Update: Integration test has been added into all of the distribution building workflow for AD plugin. 
Once we get the instructions for kibana plugin, will plan to work on it.

**Comment by weicongs-amazon** [comment]
The instruction for AD kibana plugin Integration Testing should be like: 
```
- name: Run e2e tests
        uses: cypress-io/github-action@v1

        with:

          working-directory: kibana/plugins/anomaly-detection-kibana-plugin
          command: yarn cy:run —config baseurl=http://localhost:5601
````
