### ISSUE TITLE
HELM v3: If storage class not defined in the values.yaml causes issue while installing the helm chart

### ISSUE THREAD

**Issue by samarthya** [opendistro-for-elasticsearch/opendistro-build#361]
For helm version

```
helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

You need to define storage class and create the k8s object to ensure the ```pvc``` are honoured otherwise they will be forever shown pending.

In the values.yaml by default ```storageClass``` is commented

```
     ## Open Distro master Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
```

For Helm3 you need to define a class and ensure the respective object is created.

## Example

```
storageClass: local-storage
      accessModes:
        - ReadWriteOnce
      size: 8Gi
      annotations: {}
```

```
--- # Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-local-storage
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/share/elasticsearch
```

**To Reproduce**
1. Install 'helm v3.'
2. Install the chart
3. Look at the pods, and see the error.

**Expected behavior**
With Helm 3 the storage class needs to be included as part of chart installation.

**Configuration (please complete the following information):**
 - Version 1.9
