### ISSUE TITLE
Helm chart use of secret for config

### ISSUE THREAD

**Issue by jimmyjones2** [opendistro-for-elasticsearch/opendistro-build#48]
```yaml
      volumes:
      - name: config
        secret:
          secretName: {{ template "opendistro-es.fullname" . }}-es-config
```
If this is config, why not use a configmap? That would make it easier to edit in the web interfaces of some Kubernetes web interfaces.
