### ISSUE TITLE
MAP_TILEMAP_URL or MAP_TILEMAP_OPTIONS_MAXZOOM are not taken into account

### ISSUE THREAD

**Issue by DariusMR** [opendistro-for-elasticsearch/opendistro-build#511]
**Describe the bug**

here is my docker compose

```yaml
  kibana:
    ports:
      - '127.0.0.1:5691:5601'
    image: amazon/opendistro-for-elasticsearch-kibana:1.11.0
    environment:
      ELASTICSEARCH_URL: https://elasticsearch:9200
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
      MAP_TILEMAP_URL: 'https://xxxxx/{z}/{x}/{y}.png'
      MAP_TILEMAP_OPTIONS_MAXZOOM: 19
```

Those two last value are not taken into account. but when I manually set in kibana.yml it's working

I don't know if this file bellow is used, but it's old notation for map plugin :
https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/kibana/docker/build/kibana/bin/kibana-docker
**To Reproduce**
set env file in the yaml for map

**Expected behavior**

new map layer

**Configuration (please complete the following information):**
odfe 1.11
