### ISSUE TITLE
Docker doesn't start when overriding command 

### ISSUE THREAD

**Issue by fxalgrain** [opendistro-for-elasticsearch/opendistro-build#512]
**Describe the bug**
I m using the image amazon/opendistro-for-elasticsearch in my Gitlab CI to run integration test.
So I need to enable "discovery.type=single-node" 
This can be done only by settings `command: [ "elasticsearch", "-Ediscovery.type=single-node" ]`
If you set 'discovery.type=single-node' as environnement variable, bash will failed

The problem is now, elastiscsearch won't start. We get this error:
```
java.lang.IllegalStateException: failed to load plugin class [com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin]
Likely root cause: ElasticsearchException[opendistro_security.ssl.transport.keystore_filepath or opendistro_security.ssl.transport.pemkey_filepath must be set if transport ssl is requested.]
```

**To Reproduce**
1.  `docker run --rm amazon/opendistro-for-elasticsearch:latest elasticsearch -Ediscovery.type=single-node`

**Expected behavior**
I expect to be able to start elasticsearch with some parameters without using environnement variable

**Configuration **
 - Distribution: Docker
 - Host Machine: Gitlab CI, MacOS

**Relevant information**
I fixed the issue by editing the docker-entrypoint.sh to run install_demo_configuration.sh earlier. I can open a PR if you agree with this idea

**Comment by peterzhuamazon** [comment]
Hi @fxalgrain this line works for me, can you try:
```
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" amazon/opendistro-for-elasticsearch:latest
```

**Comment by fxalgrain** [comment]
Hi @peterzhuamazon 

First of all, thanks you to have checked on your side. 

I agree with you. If we set environnement variables like this, it works as expected. But in the GitlabCI (I don't check yet on others), you could not start the container using this command line. 
You can do two things in the config file:
-  you can define global environnement variables
-  you can define the docker command.

Unfortunately, the first option will not work because "export discovery.type=single-node" is not valid in bash.
So we have to define the docker command, and this result in the error I described.

**Comment by peterzhuamazon** [comment]
Hi @fxalgrain I am not experienced with GitLabCI so I am not sure what do you mean by `could not start the container using this command line`.

`-e "discovery.type=single-node"` is part of the docker command parameter, and if you can define the docker command like your said, you should be able to use it.

Anyway this is something quite rare to us, could you just use a docker-compose file to define env var and just call docker-compose instead of docker run?

I quickly created a docker compose file and seems working well with single-node cluster:
```
version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.11.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536

    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
```

Thanks.

**Comment by peterzhuamazon** [comment]
Hi @fxalgrain there is no responses from you after 7 days, we will close this issue for now.
Please feel free to reopen it if needed.
Thanks.

**Comment by fxalgrain** [comment]
Hi Peter, 

To summarize, the goal is to start an elasticsearch with the option discovery.type=single-node in a Gitlab CI context.

I reopen the ticket to give you more details about the issue, as you have not experiences with Gitlab CI.
First of all, I agree with you that in docker CLI or in docker-compose  context, it's working fine.

But to run jobs on Gitlab CI, you have to define a .gitlab-ci.yml. 

The first idea is to mimic the docker-compose settings and to declare the env variable discovery.type=single-node
But, If you define this, you will get a Bash error. (because Gitlab runner translate it into `export discovery.type=single-node`)

To set the discovery type, the remaining option is to override the docker command. 
So in .gitlab-ci.yml, you have to define `command: [ "elasticsearch", "-Ediscovery.type=single-node" ]`
But now, you will get an error from elasticsearch : 
```
java.lang.IllegalStateException: failed to load plugin class [com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin]
Likely root cause: ElasticsearchException[opendistro_security.ssl.transport.keystore_filepath or opendistro_security.ssl.transport.pemkey_filepath must be set if transport ssl is requested.]
```

You can reproduce this on your local environnement : 
`docker run --rm amazon/opendistro-for-elasticsearch:latest elasticsearch -Ediscovery.type=single-node`

I analyse the docker-entrypoint.sh init script. And we get this error because 'install_demo_configuration.sh' is not run when command is overrided.  When `"$1" != "eswrapper"`, we execute the request command and so the script never get to bottom lines.
I think we can fix this issue (and may be some other issue) by moving down the  `"$1" != "eswrapper"` code block.

**Comment by fxalgrain** [comment]
Please find the docker-entrypoint.sh I used to fix the issue on our side
[docker-entrypoint.sh.zip](https://github.com/opendistro-for-elasticsearch/opendistro-build/files/5822078/docker-entrypoint.sh.zip)

**Comment by dawi** [comment]
@fxalgrain I am having exactly the same issue after upgrading to Elasticsearch 8.2.2.
Have you found an alternative solution, other than building your own docker image?

**Comment by fxalgrain** [comment]
@dawi I didn't inspect again the issue since last year. 
If the docker-entrypoint.sh has not change since, it's still the only way to fix it

**Comment by dawi** [comment]
GitLab allows to configure the entrypoint as well.

Therefore, the following service definition works for me:

```yaml
services:
  - name: elastic/elasticsearch:8.2.2
    alias: elasticsearch
    entrypoint:
      - "bin/elasticsearch"
      - "-Ediscovery.type=single-node"
      - "-Expack.security.enabled=false"
```

I don't know if this also applies to opensearch or advanced configuration use-cases.

**Comment by dawi** [comment]
GitLab allows to configure the entrypoint as well.

Therefore, the following service definition works for me:

```yaml
services:
  - name: elastic/elasticsearch:8.2.2
    alias: elasticsearch
    entrypoint:
      - "bin/elasticsearch"
      - "-Ediscovery.type=single-node"
      - "-Expack.security.enabled=false"
```

I don't know if this also applies to opensearch or advanced configuration use-cases.
