### ISSUE TITLE
how to configure admin user password in helm chart

### ISSUE THREAD

**Issue by chhaosh** [opendistro-for-elasticsearch/opendistro-build#558]
**Query**
What question do you have?
For https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm
Is there any way to configure admin user's password instead of default admin?/admin

**Comment by NovikovEvgeny** [comment]
you can define whole "internal_users.yaml" file using `elasticsearch.securityConfig.config.data.internal_users.yml` https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/values.yaml#L178

```yaml
elasticsearch:
  securityConfig:
    config:
      data:
        internal_users.yml: |-
          _meta:
            type: "internalusers"
            config_version: 2
          admin:
            hash: "hashed admin password"
            reserved: true
```

how to generate hash described in [the docs](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/yaml/#internal_usersyml)

or you can save whole internal users config into a separate secret and specify the reference to it 

using `elasticsearch.securityConfig.internalUsersSecret` [src](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/opendistro-es/values.yaml#L168)

More examples and info you can find [here](https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/master/helm#security-configuration)

**Comment by peterzhuamazon** [comment]
Hi @chhaosh sorry for the late reply.
Is the answer by @NovikovEvgeny resolve your issue?
Please let us know if you have any questions related to this.

Thanks.

**Comment by shibumi** [comment]
Hello everybody,
I followed this guide as follows:

```yaml
    config:
      securityConfigSecret:
      data:
       # config.yml: |-
       internal_users.yml: |-
        _meta:
            type: "internalusers"
            config_version: 2
          admin:
            hash: "REDACTED"
            reserved: true
```

but when I login into the container and do: `curl -XGET -k https://localhost:9200 -u admin:admin`

admin:admin still works, although I have changed the password. Do you have any idea?!

**Comment by shibumi** [comment]
Addition to my last post. The secret is definitely there:
```
[root@opendistro-es-13-2-master-0 elasticsearch]# cat /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
_meta:
  type: "internalusers"
  config_version: 2
admin:
  hash: "REDACTED"
  reserved: true
```

but  curl -XGET -k https://localhost:9200 -u admin:admin still does work!
