### ISSUE TITLE
Applying Security Configuration in helm charts

### ISSUE THREAD

**Issue by whiskerch** [opendistro-for-elasticsearch/opendistro-build#56]
Hi,

I am using the helm documentation here: https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/master/helm/README.md and opendistro-docs (https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/openid-connect/#elasticsearch-configuration) to setup ES in my k8s cluster. 

I am using the `securityConfig` in my values.yaml to assign the secrets that should be loaded when a pod starts, e.g.: 

```
securityConfig:
    enabled: true
    path: "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig"
    configSecret: "security-config"
    rolesSecret: "roles-config"
    rolesMappingSecret: "roles-mapping-config"
    internalUsersSecret: "internal-users-config"
    actionGroupsSecret: "action-groups-config"
    tenantsSecret: "tenants-config"
```

However, this is only picked up by the master nodes. All other nodes continue with the default values in the files. 

Looking through the helm template I can see where in the `es-master-sts.yaml` template it mounts the secret into the pod:
```
{{- if .Values.elasticsearch.securityConfig.configSecret }}
        - mountPath: {{ .Values.elasticsearch.securityConfig.path }}/config.yml
          name: security-config
          subPath: config.yml
       {{- end }}
```

However this logic is not present in any of the other charts. The same goes for all of the other values in the `securityConfig` section
