### ISSUE TITLE
Unable to deploy opendistro on kubernetes 1.20

### ISSUE THREAD

**Issue by 0pendev** [opendistro-for-elasticsearch/opendistro-build#589]
**Describe the bug**
The fixmount container of the data and master pod is not working since I've updated my cluster from 1.19 to 1.20.
When searching the logs on my node I get the following : 
```
worker:~ # cat /var/log/containers/siem-opendistro-es-data-0_skube-system_fixmount-577d90bbae108be23099e91eda249d84e82c8222f5f5aa5c94aa4f88cbb1f209.log
2021-01-31T19:27:47.868919562+00:00 stderr F chown: /usr/share/elasticsearch/data: Operation not permitted
2021-01-31T19:27:47.868919562+00:00 stderr F chown: /usr/share/elasticsearch/data: Operation not permitted

worker:~ # cat /var/log/containers/siem-opendistro-es-master-0_skube-system_fixmount-69d310e7764841bcf76374c04f317185b27f1b9b65c1b0e5232a25fac274ff88.log
2021-01-31T19:27:29.883026741+00:00 stderr F chown: /usr/share/elasticsearch/data: Operation not permitted
2021-01-31T19:27:29.883026741+00:00 stderr F chown: /usr/share/elasticsearch/data: Operation not permitted

```

My volumes are correctly bound : 
```
skubeguy@localhost:~/Documents/deployment> kubectl get pvc
NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            AGE
data-siem-opendistro-es-data-0     Bound    pvc-aeaf8af8-0845-42f1-9b01-98d105dec8b9   8Gi        RWO            skube-default-storage   25m
data-siem-opendistro-es-master-0   Bound    pvc-c99ac213-b47e-44e0-86f5-35dc8f9997c4   8Gi        RWO            skube-default-storage   25m

```

Here is the states of my pods : 
```
kubeguy@localhost:~/Documents/deployment> kubectl get pods 
NAME                                               READY   STATUS                  RESTARTS   AGE
siem-opendistro-es-client-7f7cbcb544-w9f5j   1/1     Running                 0          5m4s
siem-opendistro-es-data-0                    0/1     Init:CrashLoopBackOff   5          4m52s
siem-opendistro-es-kibana-69d4f6f7c7-z8qhg   1/1     Running                 0          5m4s
siem-opendistro-es-master-0                  0/1     Init:CrashLoopBackOff   5          5m4s
```

**To Reproduce**

I'm using [Kubic](https://kubic.opensuse.org/) : 
```
kubicctl init
kubicctl node add worker
git clone https://github.com/opendistro-for-elasticsearch/opendistro-build
helm install siem ./opendistro-build/helm/opendistro-es -f values.yml
```
I'm using the following values : 
```
kibana:
  ingress:
    enabled: true
    hosts: ["siem.local"]
  replicas: 1

elasticsearch:
  client:
    ingress:
      enabled: true
      hosts: ["elastic.local"]
    replicas: 1
  master:
    replicas: 1
    storageClassName: "nfs-default-storage"
    storage: "10Gi"
  data:
    replicas: 1
    storageClassName: "nfs-default-storage"
    storage: "10Gi"
```

**Expected behavior**
When using kubernetes 1.19 the states of the pods changed to READY and everything was working fine.

**Configuration (please complete the following information):**
   OpenSUSE Kubic
   Helm Installed from the master branch of this registry.

**Relevant information**
 
I tried to add CHOWN (and privileged) capabilities to the container but it did not solved the issue.
