### ISSUE TITLE
Injecting Secrets from Google Cloud Secret Manager into Pods

### ISSUE THREAD

**Issue by rileyhun** [opendistro-for-elasticsearch/opendistro-build#690]
**Is your feature request related to a problem? Please describe.**
I want to use a vault to store all the admin secrets/passwords and it would be great if we could inject secrets from this vault directly into the K8s pods of this helm deployment. 

**Describe the solution you'd like**
I have [Berglas](https://github.com/GoogleCloudPlatform/berglas/tree/main/examples/kubernetes) set up and I want to reference the secret from Google Cloud Secret Manager, as shown below. 

```
env:
        - name: API_KEY
          value: sm://PROJECT_ID/my-secret
```

I don't know if it is possible to add this as an environment variable that can then be referenced in the SecurityConfig? 

I think the config should look something like this:
```
kibana:
  extraEnvs:
      - name: SERVER_BASEPATH
        value: "/kibana"
      - name: ELASTICSEARCH_USERNAME
        value: "admin"
      - name: ELASTICSEARCH_PASSWORD
        value: sm://PROJECT_ID/seldon-elastic-secret
    serviceAccount:
      name: secretsinvoker
    config:
      elasticsearch.username: ${ELASTICSEARCH_USERNAME}
      elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
elasticsearch:
  serviceAccount:
    name: secretsinvoker
  extraEnvs:
    - name: ELASTICSEARCH_USERNAME
      value: "admin"
    - name: ELASTICSEARCH_PASSWORD
      value: sm://PROJECT_ID/seldon-elastic-secret
```
