### ISSUE TITLE
Problem with setting up security config via values.yml

### ISSUE THREAD

**Issue by LakshithaSLT** [opendistro-for-elasticsearch/opendistro-build#754]
Faced the below problem while I tried to overwrite config.yaml via vlaues.yaml. 

coalesce.go:199: warning: destination for securityConfigSecret is a table. Ignoring non-table value <nil>

Here is the my test config.
```
    config:
      securityConfigSecret:
        config.yml: |-
          _meta:
            type: "config"
            config_version: 2
          config:
            dynamic:
              filtered_alias_mode: "none"
              disable_rest_auth: false
              disable_intertransport_auth: false
              respect_request_indices_options: false
              license: null
              kibana:
                multitenancy_enabled: true
```
