### ISSUE TITLE
Helm README.md Security Configuration incorrect

### ISSUE THREAD

**Issue by mconner** [opendistro-for-elasticsearch/opendistro-build#758]
**Describe the bug**
The Helm README.md [Security Configuration](https://github.com/opendistro-for-elasticsearch/opendistro-build/tree/main/helm#security-configuration) section 
shows:

> or You can specify all the security configurations in the values.yaml file as
> ```
> securityConfig:
>   enabled: true
>   path: "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig"
>   securityConfigSecret:
>   data: {}
>     # config.yml: |-
>     # internal_users.yml: |-
>     # roles.yml: |-
>     # rolesMapping.yml: |-
>     # tenants.yml: |-
> ```
> 

However, the structure is actually expected to be:
```
securityConfig:
  enabled: true
  path: "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig"
  config:
    securityConfigSecret:
    data: {}
    # config.yml: |-
    # internal_users.yml: |-
    # roles.yml: |-
    # rolesMapping.yml: |-
    # tenants.yml: |-
```
That is, there's a `config `between `securityConfig `and `securityConfigSecret`, as evidenced by [es-security-config.yaml](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/4d440b7473e58651608070f0f5d446c4736e1ccf/helm/opendistro-es/templates/elasticsearch/es-security-config.yaml#L1)
`{{- if and .Values.elasticsearch.securityConfig.config.securityConfigSecret .Values.elasticsearch.securityConfig.config.data }}`

**To Reproduce**
Read the Helm README.md

**Expected behavior**
Accurate documentation.

**Configuration (please complete the following information):**
na

**Relevant information**
